name: dua
description: "Redesigned version of My Dua app in flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  provider: ^6.1.2
  flutter_native_splash: ^2.3.10
  webview_flutter: ^4.5.0
  bottom_navbar_player: ^0.1.0
  marquee: ^2.2.3
  adhan: ^2.0.0+1
  hijri: ^3.0.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  html: ^0.15.4
  connectivity_plus: ^6.0.1
  quickalert: ^1.1.0
  wakelock: ^0.6.2
  intl: ^0.19.0
  change_case: ^2.0.1
  animated_custom_dropdown: ^3.0.0
  geolocator: ^11.0.0
  app_settings: ^5.1.1
  firebase_auth: ^4.17.8
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_native_splash:
    color: "#ffffff"
    image: assets/playstore.png

flutter:
  uses-material-design: true

  assets:
    - assets/playstore.png
    - assets/images/
    - assets/audios/